/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, FunctionResult, BamlCtxManager, Image, Audio, Pdf, Video, FunctionLog,
HTTPRequest } from "@boundaryml/baml"
import { toBamlError, BamlStream, BamlAbortError, Collector, ClientRegistry } from "@boundaryml/baml"
import type { Checked, Check, RecursivePartialNull as MovedRecursivePartialNull } from "./types"
import type { partial_types } from "./partial_types"
import type * as types from "./types"
import type {Group, GroupResponse, PreferencesResponse, Resume} from "./types"
import type TypeBuilder from "./type_builder"
import { AsyncHttpRequest, AsyncHttpStreamRequest } from "./async_request"
import { LlmResponseParser, LlmStreamParser } from "./parser"
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX,
DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"
import type * as events from "./events"

/**
* @deprecated Use RecursivePartialNull from 'baml_client/types' instead.
*/
export type RecursivePartialNull<T> = MovedRecursivePartialNull<T>

    type TickReason = "Unknown";

    type BamlCallOptions<WatchersT = never> = {
    tb?: TypeBuilder
    clientRegistry?: ClientRegistry
    client?: string
    collector?: Collector | Collector[]
    env?: Record<string, string | undefined>
      tags?: Record<string, string>
        signal?: AbortSignal
        onTick?: (reason: TickReason, log: FunctionLog | null) => void
        watchers?: WatchersT
        }

        export class BamlAsyncClient {
        private runtime: BamlRuntime
        private ctxManager: BamlCtxManager
        private streamClient: BamlStreamClient
        private httpRequest: AsyncHttpRequest
        private httpStreamRequest: AsyncHttpStreamRequest
        private llmResponseParser: LlmResponseParser
        private llmStreamParser: LlmStreamParser
        private bamlOptions: BamlCallOptions

        constructor(runtime: BamlRuntime, ctxManager: BamlCtxManager, bamlOptions?: BamlCallOptions) {
        this.runtime = runtime
        this.ctxManager = ctxManager
        this.streamClient = new BamlStreamClient(runtime, ctxManager, bamlOptions)
        this.httpRequest = new AsyncHttpRequest(runtime, ctxManager)
        this.httpStreamRequest = new AsyncHttpStreamRequest(runtime, ctxManager)
        this.llmResponseParser = new LlmResponseParser(runtime, ctxManager)
        this.llmStreamParser = new LlmStreamParser(runtime, ctxManager)
        this.bamlOptions = bamlOptions || {}
        }

        withOptions(bamlOptions: BamlCallOptions) {
        return new BamlAsyncClient(this.runtime, this.ctxManager, bamlOptions)
        }

        get stream() {
        return this.streamClient
        }

        get request() {
        return this.httpRequest
        }

        get streamRequest() {
        return this.httpStreamRequest
        }

        get parse() {
        return this.llmResponseParser
        }

        get parseStream() {
        return this.llmStreamParser
        }

        
        async Clarifier(
        conversationMessages: string[],preferences: string[],
        __baml_options__?: BamlCallOptions<never>
        ): Promise<string> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.Clarifier(
          conversationMessages,preferences,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );

            // Resolve client option to clientRegistry (client takes precedence)
            let __clientRegistry__ = __options__.clientRegistry;
            if (__options__.client) {
              __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
              __clientRegistry__.setPrimary(__options__.client);
            }

            const __raw__ = await this.runtime.callFunction(
            "Clarifier",
            {
            "conversationMessages": conversationMessages,"preferences": preferences
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __clientRegistry__,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as string
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async ExtractResume(
        resume: string,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.Resume> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.ExtractResume(
          resume,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );

            // Resolve client option to clientRegistry (client takes precedence)
            let __clientRegistry__ = __options__.clientRegistry;
            if (__options__.client) {
              __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
              __clientRegistry__.setPrimary(__options__.client);
            }

            const __raw__ = await this.runtime.callFunction(
            "ExtractResume",
            {
            "resume": resume
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __clientRegistry__,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.Resume
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async PreferenceMatcher(
        userMessages: string[],preferences: string[],
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.PreferencesResponse> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.PreferenceMatcher(
          userMessages,preferences,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );

            // Resolve client option to clientRegistry (client takes precedence)
            let __clientRegistry__ = __options__.clientRegistry;
            if (__options__.client) {
              __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
              __clientRegistry__.setPrimary(__options__.client);
            }

            const __raw__ = await this.runtime.callFunction(
            "PreferenceMatcher",
            {
            "userMessages": userMessages,"preferences": preferences
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __clientRegistry__,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.PreferencesResponse
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async Replier(
        conversationMessages: string[],groups: types.Group[],
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.GroupResponse> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.Replier(
          conversationMessages,groups,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );

            // Resolve client option to clientRegistry (client takes precedence)
            let __clientRegistry__ = __options__.clientRegistry;
            if (__options__.client) {
              __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
              __clientRegistry__.setPrimary(__options__.client);
            }

            const __raw__ = await this.runtime.callFunction(
            "Replier",
            {
            "conversationMessages": conversationMessages,"groups": groups
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __clientRegistry__,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.GroupResponse
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
            }

            class BamlStreamClient {
            private runtime: BamlRuntime
            private ctxManager: BamlCtxManager
            private bamlOptions: BamlCallOptions

            constructor(runtime: BamlRuntime, ctxManager: BamlCtxManager, bamlOptions?: BamlCallOptions) {
            this.runtime = runtime
            this.ctxManager = ctxManager
            this.bamlOptions = bamlOptions || {}
            }

            
            Clarifier(
            conversationMessages: string[],preferences: string[],
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<string, string>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for Clarifier", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );

                // Resolve client option to clientRegistry (client takes precedence)
                let __clientRegistry__ = __options__.clientRegistry;
                if (__options__.client) {
                  __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
                  __clientRegistry__.setPrimary(__options__.client);
                }

                const __raw__ = this.runtime.streamFunction(
                "Clarifier",
                {
                "conversationMessages": conversationMessages,"preferences": preferences
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __clientRegistry__,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<string, string>(
                  __raw__,
                  (a): string => a,
                  (a): string => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            ExtractResume(
            resume: string,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.Resume, types.Resume>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for ExtractResume", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );

                // Resolve client option to clientRegistry (client takes precedence)
                let __clientRegistry__ = __options__.clientRegistry;
                if (__options__.client) {
                  __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
                  __clientRegistry__.setPrimary(__options__.client);
                }

                const __raw__ = this.runtime.streamFunction(
                "ExtractResume",
                {
                "resume": resume
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __clientRegistry__,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.Resume, types.Resume>(
                  __raw__,
                  (a): partial_types.Resume => a,
                  (a): types.Resume => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            PreferenceMatcher(
            userMessages: string[],preferences: string[],
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.PreferencesResponse, types.PreferencesResponse>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for PreferenceMatcher", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );

                // Resolve client option to clientRegistry (client takes precedence)
                let __clientRegistry__ = __options__.clientRegistry;
                if (__options__.client) {
                  __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
                  __clientRegistry__.setPrimary(__options__.client);
                }

                const __raw__ = this.runtime.streamFunction(
                "PreferenceMatcher",
                {
                "userMessages": userMessages,"preferences": preferences
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __clientRegistry__,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.PreferencesResponse, types.PreferencesResponse>(
                  __raw__,
                  (a): partial_types.PreferencesResponse => a,
                  (a): types.PreferencesResponse => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            Replier(
            conversationMessages: string[],groups: types.Group[],
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.GroupResponse, types.GroupResponse>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for Replier", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );

                // Resolve client option to clientRegistry (client takes precedence)
                let __clientRegistry__ = __options__.clientRegistry;
                if (__options__.client) {
                  __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
                  __clientRegistry__.setPrimary(__options__.client);
                }

                const __raw__ = this.runtime.streamFunction(
                "Replier",
                {
                "conversationMessages": conversationMessages,"groups": groups
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __clientRegistry__,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.GroupResponse, types.GroupResponse>(
                  __raw__,
                  (a): partial_types.GroupResponse => a,
                  (a): types.GroupResponse => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
                  }

                  export const b = new BamlAsyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME,
                  DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)